export const products = [
  {
    id: 1,
    title: "Colgante Mohanna",
    price: 200,
    stock: 21,
    description: "Colgante artesanal",
    category: "colgante",
    url: "https://res.cloudinary.com/dttpgbmdx/image/upload/v1739045819/colgante7_hvqt0q.jpg",
  },
  {
    id: 2,
    title: "Colgante Pilucha",
    price: 500,
    stock: 12,
    description: "Colgante artesanal",
    category: "colgante",
    url: "https://res.cloudinary.com/dttpgbmdx/image/upload/v1739045818/colgante6_nfcxbn.jpg",
  },
  {
    id: 3,
    title: "Tapiz Kuan",
    price: 800,
    stock: 6,
    description: "Tapiz artesanal",
    category: "tapiz",
    url: "https://res.cloudinary.com/dttpgbmdx/image/upload/v1739045834/tapiz3_bz9qsj.jpg",
  },
  {
    id: 4,
    title: "Tapiz Marilau",
    price: 900,
    stock: 10,
    description: "Tapiz artesanal",
    category: "tapiz",
    url: "https://res.cloudinary.com/dttpgbmdx/image/upload/v1739045834/tapiz_xhgfeo.jpg",
  },
];
